### PR TITLE
Expand paths before passing to libxml2

### LINKED ISSUE #80: caught segfault trying write_xml
Caught segfault while trying to download a file with `xml2::write_xml`. 

Here's the log:
```
tt <- rcrossref::cr_cn("10.5194/nhess-13-1285-2013", "crossref-tdm")
xml2::write_xml(tt, file = "~/Downloads/")

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("xml2_doc_write", PACKAGE = "xml2", x, path)
 2: doc_write(x$doc, file)
 3: write_xml.xml_document(tt, file = "~/Downloads/")
 4: xml2::write_xml(tt, file = "~/Downloads/")
```

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #80

### CODE REVIEW

**Comment by hadley** [comment]
Might be better to do this in C with `R_ExpandFileName` ?

**Comment by jimhester** [comment]
It looks like that is what `path.expand()` is doing (https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/main/platform.c#L1839-L1860)

**Comment by hadley** [comment]
Right, it just feels a little safer to do this in C to me.

**Comment by jimhester** [comment]
Ok it is so (https://github.com/hadley/xml2/pull/86/commits/1c303ccf166e1a7f1c1896957fd16b0dce7b0b70)

**Comment by hadley** [comment]
Perfect. Can you add a bullet to news too?

**Comment by jimhester** [comment]
done

**Pull request merged**
